#!/bin/bash
# The logic to start up your application should be put in this
# script. The application will work only if it binds to
# $OPENSHIFT_DIY_IP:8080
#nohup $OPENSHIFT_REPO_DIR/diy/testrubyserver.rb $OPENSHIFT_DIY_IP $OPENSHIFT_REPO_DIR/diy |& /usr/bin/logshifter -tag diy &

cd $OPENSHIFT_REPO_DIR
nohup java -jar target/peach-1.0-SNAPSHOT.jar > ${OPENSHIFT_DIY_LOG_DIR}/peach.log 2>&1 &